// <auto-generated />
using ApiGerenciadorSalas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiGerenciadorSalas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241211154311_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiGerenciadorSalas.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cadeiras")
                        .HasColumnType("integer");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChaveReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("ApiGerenciadorSalas.Entities.SalaSoftware", b =>
                {
                    b.Property<int>("SalaId")
                        .HasColumnType("integer");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("integer");

                    b.HasKey("SalaId", "SoftwareId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SalaSoftwares");
                });

            modelBuilder.Entity("ApiGerenciadorSalas.Entities.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("ApiGerenciadorSalas.Entities.SalaSoftware", b =>
                {
                    b.HasOne("ApiGerenciadorSalas.Entities.Sala", "Sala")
                        .WithMany("SalaSoftwares")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiGerenciadorSalas.Entities.Software", "Software")
                        .WithMany("SalaSoftwares")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("ApiGerenciadorSalas.Entities.Sala", b =>
                {
                    b.Navigation("SalaSoftwares");
                });

            modelBuilder.Entity("ApiGerenciadorSalas.Entities.Software", b =>
                {
                    b.Navigation("SalaSoftwares");
                });
#pragma warning restore 612, 618
        }
    }
}
